# coding: utf-8

"""
    API Teatro Colon

    API para la reserva de butacas de teatro Colon

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """ DefaultApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.default_api.DefaultApi()

    def tearDown(self):
        pass

    def test_planta_cancelar(self):
        """
        Test case for planta_cancelar

        Cancela la butaca ubicada en columna y fila. Retorna -1 si la butaca no pudo ser cancelada y 0 en caso de que se haya cancelado
        """
        pass

    def test_planta_leer_get(self):
        """
        Test case for planta_leer_get

        Retorna el estado de la planta
        """
        pass

    def test_planta_vender_get(self):
        """
        Test case for planta_vender_get

        Vende la butaca ubicada en columna y fila. Retorna -1 si la butaca no pudo ser vendida y 0 en caso de que se haya vendido
        """
        pass


if __name__ == '__main__':
    unittest.main()
