# coding: utf-8

"""
    API Teatro Colon

    API para la reserva de butacas de teatro Colon

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.butaca import Butaca


class TestButaca(unittest.TestCase):
    """ Butaca unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testButaca(self):
        """
        Test Butaca
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = swagger_client.models.butaca.Butaca()
        pass


if __name__ == '__main__':
    unittest.main()
