# coding: utf-8

"""
    API Teatro Colon

    API para la reserva de butacas de teatro Colon

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from .butaca import Butaca
