# coding: utf-8

"""
    API Teatro Colon

    API para la reserva de butacas de teatro Colon

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class Butaca(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'fila': 'str',
        'columna': 'str',
        'estado': 'str'
    }

    attribute_map = {
        'fila': 'fila',
        'columna': 'columna',
        'estado': 'estado'
    }

    def __init__(self, fila=None, columna=None, estado=None):
        """
        Butaca - a model defined in Swagger
        """

        self._fila = None
        self._columna = None
        self._estado = None

        if fila is not None:
          self.fila = fila
        if columna is not None:
          self.columna = columna
        if estado is not None:
          self.estado = estado

    @property
    def fila(self):
        """
        Gets the fila of this Butaca.

        :return: The fila of this Butaca.
        :rtype: str
        """
        return self._fila

    @fila.setter
    def fila(self, fila):
        """
        Sets the fila of this Butaca.

        :param fila: The fila of this Butaca.
        :type: str
        """

        self._fila = fila

    @property
    def columna(self):
        """
        Gets the columna of this Butaca.

        :return: The columna of this Butaca.
        :rtype: str
        """
        return self._columna

    @columna.setter
    def columna(self, columna):
        """
        Sets the columna of this Butaca.

        :param columna: The columna of this Butaca.
        :type: str
        """

        self._columna = columna

    @property
    def estado(self):
        """
        Gets the estado of this Butaca.

        :return: The estado of this Butaca.
        :rtype: str
        """
        return self._estado

    @estado.setter
    def estado(self, estado):
        """
        Sets the estado of this Butaca.

        :param estado: The estado of this Butaca.
        :type: str
        """

        self._estado = estado

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, Butaca):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
