---
swagger: "2.0"
info:
  description: "API para la reserva de butacas de teatro Colon"
  version: "1.0.0"
  title: "API Teatro Colon"
basePath: "/v1"
schemes:
- "http"
paths:
  /planta/leer:
    get:
      summary: "Retorna el estado de la planta"
      operationId: "planta_leer_get"
      produces:
      - "application/json"
      parameters:
      - name: "fila"
        in: "query"
        description: "Numero de la fila a consular"
        required: false
        type: "integer"
      - name: "columna"
        in: "query"
        description: "Columna a consular"
        required: false
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Butaca"
        400:
          description: "Invalid status value"
      x-swagger-router-controller: "swagger_server.controllers.default_controller"
  /planta/vender:
    get:
      summary: "Vende la butaca ubicada en columna y fila. Retorna -1 si la butaca\
        \ no pudo ser vendida y 0 en caso de que se haya vendido"
      operationId: "planta_vender_get"
      produces:
      - "application/json"
      parameters:
      - name: "fila"
        in: "query"
        description: "Numero de la fila a vender"
        required: true
        type: "integer"
      - name: "columna"
        in: "query"
        description: "Columna a vender"
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "integer"
        400:
          description: "Invalid status value"
      x-swagger-router-controller: "swagger_server.controllers.default_controller"
definitions:
  Butaca:
    type: "object"
    properties:
      fila:
        type: "string"
      columna:
        type: "string"
      estado:
        type: "string"
