# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class Butaca(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, fila: str=None, columna: str=None, estado: str=None):
        """
        Butaca - a model defined in Swagger

        :param fila: The fila of this Butaca.
        :type fila: str
        :param columna: The columna of this Butaca.
        :type columna: str
        :param estado: The estado of this Butaca.
        :type estado: str
        """
        self.swagger_types = {
            'fila': str,
            'columna': str,
            'estado': str
        }

        self.attribute_map = {
            'fila': 'fila',
            'columna': 'columna',
            'estado': 'estado'
        }

        self._fila = fila
        self._columna = columna
        self._estado = estado

    @classmethod
    def from_dict(cls, dikt) -> 'Butaca':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Butaca of this Butaca.
        :rtype: Butaca
        """
        return deserialize_model(dikt, cls)

    @property
    def fila(self) -> str:
        """
        Gets the fila of this Butaca.

        :return: The fila of this Butaca.
        :rtype: str
        """
        return self._fila

    @fila.setter
    def fila(self, fila: str):
        """
        Sets the fila of this Butaca.

        :param fila: The fila of this Butaca.
        :type fila: str
        """

        self._fila = fila

    @property
    def columna(self) -> str:
        """
        Gets the columna of this Butaca.

        :return: The columna of this Butaca.
        :rtype: str
        """
        return self._columna

    @columna.setter
    def columna(self, columna: str):
        """
        Sets the columna of this Butaca.

        :param columna: The columna of this Butaca.
        :type columna: str
        """

        self._columna = columna

    @property
    def estado(self) -> str:
        """
        Gets the estado of this Butaca.

        :return: The estado of this Butaca.
        :rtype: str
        """
        return self._estado

    @estado.setter
    def estado(self, estado: str):
        """
        Sets the estado of this Butaca.

        :param estado: The estado of this Butaca.
        :type estado: str
        """

        self._estado = estado

